services:
  - type: web
    name: suitecrm
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_TYPE
        value: postgres
      - key: DB_HOST
        fromDatabase:
          name: suitecrm-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: suitecrm-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: suitecrm-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: suitecrm-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: suitecrm-db
          property: password

databases:
  - name: suitecrm-db
    plan: free
    databaseName: suitecrm
    user: suitecrmuser
